### ISSUE TITLE
byteswap.h is missing

### ISSUE THREAD

**Issue by melomac** [quarkslab/binbloom#5]
Hi

I gave a quick try at `binbloom` on macOS and was pleasantly surprised on how effective it is with Mach-O slices!

Would you please be so kind to consider making it "accessible" to BSD users by removing Linux only header file [`byteswap.h`](https://github.com/quarkslab/binbloom/blob/626d60aa3d72953854716793855fe718c61e88f5/src/helpers.h#L7) dependency?

Thank you!

**Comment by virtualabs** [comment]
Hi, thanks for reporting this issue ! I added cross-platform support for byte swapping that should work fine with BSD/OS X/Solaris/Linux, but since I don't own a BSD system I was not able to check if this fix solves the problem. This fix has been pushed to the master branch, so please test it (don't forget to clean and re-run configure since configure.ac has been changed) and tell me if the problem is solved on BSD.

**Comment by melomac** [comment]
I cleaned my local repo and was able to build and run `binbloom` on macOS successfully.
`binbloom` finds Mach-O files for Apple Silicon and Intel platforms at the expected location.
Many thanks!

**Comment by virtualabs** [comment]
You're welcome, and thank you for reporting this issue. Glad to see that `binbloom` works on Mach-O files too :+1: !
